use_frameworks!

platform :ios, '10.0'

target 'HDCommon_Example' do
  pod 'HDCommon', :path => '../'
  pod 'DoraemonKit'
  pod 'CocoaLumberjack'
  
  target 'HDCommon_Tests' do
    inherit! :search_paths

    
  end
end
